manager/test_run_loggers.py

Also suppressed ResourceWarning messages about unclosed files.

Added a little more time to wait for TextFileWrite to finish.

---

logger/readers/test_text_file_reader.py
logger/readers/text_file_reader.py

There are still a few TODO's in the code (and a question), but it's mostly working, so I think it's ready for feedback.

Issue #19: implemented seek() and read_range() in TextFileReader

---

logger/readers/logfile_reader.py
logger/readers/test_logfile_reader.py

I finally had some time to work on this. It's not perfect, but at least this time it matches the definitions and descriptions of seek_time() and read_time_range() in TimestampedReader.
Caveats:
1) I didn't address the issue of out-of-order records. I think the hardest part of that is just deciding what the desired behavior is. The current behavior is probably adequate for many use cases as long as the records are approximately sorted.
2) It doesn't do things like skip over entire files based on timestamps, or binary search within a file. In order to do that, I think it would be necessary for LogfileReader to stop using TextFileReader and instead do its own file handling, because TextFileReader doesn't know about time, and even if it did, skipping over a file (without counting the records …

Implemented seek_time() and read_time_range() for LogfileReader.

---

database/mongo_connector.py
database/mongo_record_connector.py
database/mongo_settings.py.dist
database/setup_mongo_connector.sh
database/test_mongo_connector.py
database/test_mongo_record_connector.py

The setup might still be a little rough but I've got the connector passing both unit tests

Initial version of MongoDB-base database connector

---

logger/transforms/timestamp_transform.py

Add optional custom separator between timestamp and data string

specify custom separator

---

display/html/d3_demo.html
display/js/widgets/d3_widgets.js

D3 based DialWidget

---

display/html/d3_demo.html
display/js/widgets/d3_widgets.js

This works for me now with a fixed size div. I'm sure there's a simpler way to do this, but hopefully this will work for you.

Make D3DialWidget center itself in its containing div.

---

.gitignore
logger/listener/listen.py
logger/settings.py.dist
logger/writers/influxdb_writer.py
test/NBP1406/NBP1406_cruise_influx.yaml

Initial import of influxDB_writer, settings file template and associated changes

Initial import of influxDB_writer

---

logger/transforms/format_transform.py

Requesting a pull from issue_201b to dev

Issue 201b

---

django_gui/templates/django_gui/login_user.html
django_gui/urls.py
django_gui/views.py

Edit urls.py, views.py to include the code for the login page and also add the login_user.html file.
Now, it works properly and it is easier to be maintainable.

Add the new login_user page

---

nmea_checksum_transform.py
test_nmea_checksum_transform.py

test_nmea_checksum_transform.py is the unittest script for nmea_checksum_transform.py

NMEA Checksum Transform

---

.gitignore
local/rcrv/modules/coriolix_connector.py
local/rcrv/modules/coriolix_writer.py
local/rcrv/settings.py.dist
local/rcrv/setup.sh
local/rcrv/update_cruise_definition.py

Migrated PostgreSQL naming to CORIOLIX as it is different then a PostgreSQL port of the MySQL database connector and writer.
Updated  setup.sh and update_cruise_definition.py  script to match. 
Adding Coriolix-specific settings.py.dist file.
None of this has been tested or even run.  The connector was ported from the PostgreSQL Connector.

CORIOLIX Writer Stub

---

local/rcrv/modules/coriolix_connector.py
local/rcrv/modules/coriolix_writer.py

taking another look at the writer reveled the writer did not correctly writer to the correct table.

Fixing some obvious errors

---

database/postgresql_connector.py
database/settings.py.dist
database/setup_mysql_connector.sh
database/setup_postgresql_connector.sh
database/test_postgresql_connector.py
django_gui/templates/django_gui/login_user.html
django_gui/urls.py
django_gui/views.py
docs/parsing.md
local/rcrv/modules/postgres_writer.py
local/rcrv/setup.sh
local/rcrv/update_cruise_definition.py
logger/readers/mqtt_reader.py
logger/readers/test_mqtt_reader.py
logger/transforms/nmea_checksum_transform.py
logger/transforms/parse_transform.py
logger/transforms/test_nmea_checksum_transform.py
logger/utils/record_parser.py
logger/utils/test_record_parser.py
logger/writers/influxdb_writer.py
logger/writers/logfile_writer.py
logger/writers/mqtt_writer.py
server/logger_manager.py

Initial stab at developing the postgreSQL connector for OpenRVDAS.  Includes associated unit tests which match the tests used for the MySQL connector.  In developing the PostgreSQL connector I found some potential errors in the MySQL connector which caused the unit tests to fail.  This import includes fixes to the MySQL connector and unit tests.

Rcrv postgres connector

---

logger/listener/listen.py

Noticed NMEATransform missing from listen.py

Add missing references to NMEATransform

---

logger/writers/file_writer.py

Adds ability to truncate files every x hours or x minutes.  Before committing please ponder any negative performance impacts cause by the more complex processing of the file name... this is working for my test case but may be a problem for higher data rate streams.

File writer - interval

---

utils/install_openrvdas.sh

fixed issue with mysql installation on ubuntu 20.04, removing identified by from grant command.

mysql error grant error

---

logger/writers/file_writer.py
logger/writers/logfile_writer.py
logger/writers/test_file_writer.py
logger/writers/test_text_file_writer.py
logger/writers/text_file_writer.py

Code changes and update unit tests need to implement #314

added ability to add headers to text_files, log_files & text-based files

---

logger/readers/reader.py

add option for bytes to be interpreted as hexadecimal but with string type (i.e. we are effectively not decoding the bytes, just changing the representation/type)

Reader hex string

---

logger/readers/polled_serial_reader.py
logger/readers/reader.py
logger/readers/serial_reader.py
logger/writers/serial_writer.py
logger/writers/test_serial_writer.py
logger/writers/udp_writer.py
logger/writers/writer.py

Hey, Pablo!  Here's my next batch of fixes!  Very similar to the ones you just reviewed for UDPWriter, this time I was working on serial data.  I'm not even using serial here at the moment, but test suite failures caught my eye while I was compare-n-contrasting working on the UDP stuff.
I also included a commit that makes the 2 trivial changes you mentioned reviewing PR #345.

Fixes for SerialWriter and SerialReader

---

logger/readers/reader.py
logger/writers/file_writer.py
logger/writers/writer.py

Hey, Pablo!  Here's a batch of fixes I made while making FileWriter work with raw/binary output.

Make FileWriter support raw/binary output and other fixes

---

logger/listener/listen.py
logger/readers/test_udp_reader.py
logger/readers/udp_reader.py
logger/writers/tcp_writer.py
logger/writers/udp_writer.py

Hey, Pablo!  Happy weekend!  Don't read this until Monday, unless you really want to.  :-)  This batch of commits makes changes similar to the ones in recent UDPWriter and TCPWriter pull requests.  Improvements have been made to name resolution, text and raw/binary input handling, multicast and broadcast handling, optimized buffer sizes, configurable socket options, removal of TCP-centric conditional code, bet test coverage, etc.  This will be followed up with a "Replace NetworkReader with TCPReader" pull request once I've finished testing that code.

Revamp UDPReader

---

logger/transforms/nmea_transform.py
logger/transforms/test_nmea_transform.py

add choice for which nmeas to use, add dpt and stn nmeas, add test

new functionality for nmea transform

---

logger/transforms/geofence_transform.py
logger/transforms/test_geofence_transform.py

Added requested functionality for issue_385

---

logger/readers/test_udp_reader.py
logger/readers/udp_reader.py

Please take a close look at this one... it passes the unit tests but there may be room for optimization.
Had to change the default eol to None to avoid breaking all kinds of things.

Attempt at fix for #387

---

.gitignore
django_gui/api_views.py
django_gui/urls.py
django_gui/views.py

Pablo asked me to take a look at this. It all looks good to me just some minor tidying up, only change I would make is to group the endpoints which i've commented on below. 
I wasn't able to tag @gabesargeant for a review but obviously keen to know what you think as you did all the work so far!

Django Rest Framework - Code review

---

django_gui/api_views.py

Added a mechanism to extend the core API endpoints in a way that hopefully reduces merge conflicts.

Example custom api endpoints

---

contrib/config_templates/serial_reader_config_template.yaml
contrib/logger_templates/serial_logger_template_new.yaml
test/NBP1406/NBP1406_cruise_new.yaml

I submit and admit defeat...  Best I could do was build the templates and new config files

Tried to add config_templates to read_config but failed

---

django_gui/static/django_gui/websocket.js

This also resolves #337, right?

Resolves #446 - Dynamically build cds-ws URL to account for accessing OpenRVDAS via port forwarding

---

logger/readers/reader.py
logger/readers/serial_reader.py
logger/readers/udp_reader.py

Low urgency, but here's my interpretation of the change needed to fit WHOI requirements.

#454 - added keep_empty_records flag

---

server/logger_runner.py

Resolves #463 - try terminating process gently, and escalate if failing.
